In [16]:
import numpy as np

arr = np.arange(1, 11)
print(arr)
arr = np.random.randint(1, 11, (2, 3))
print(arr)
arr = np.identity(3, dtype=np.float16)
# arr = np.eye(3, dtype=np.float16)
print(arr)
arr = np.random.randint(-1, 3, (3, 2, 5, 4))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[4 9 9]
 [9 4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[[[ 1  1  2  0]
   [ 1  1  2  0]
   [ 2  1  1 -1]
   [ 1  0  2  2]
   [-1  2  0  2]]

  [[-1  2  2  1]
   [ 1 -1  1 -1]
   [-1  2 -1  2]
   [ 2  2  2  1]
   [ 2  1  2 -1]]]


 [[[ 1  2 -1  1]
   [ 1 -1 -1  2]
   [-1  1  1  2]
   [ 0 -1  1  2]
   [ 0  1  0 -1]]

  [[ 2 -1  2  2]
   [ 1  0 -1  1]
   [ 1 -1  2  2]
   [-1  0 -1 -1]
   [ 0 -1  2  2]]]


 [[[-1  1  2 -1]
   [ 1  1  1  1]
   [ 0  0  0 -1]
   [ 1  2 -1  1]
   [ 0  2 -1  0]]

  [[ 2  1 -1  2]
   [-1 -1  0  2]
   [ 0  1  0  0]
   [-1  0  0 -1]
   [ 2  1  2  1]]]]


In [21]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr[1,2])
print(arr[:2])
print(arr[:,2])
print(arr[::2, ::2])

6
[[1 2 3]
 [4 5 6]]
[3 6 9]
[[1 3]
 [7 9]]


In [24]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
print([a[i] + b[i] for i in range(len(a))])
c = a**2
print(c)
print(np.dot(a, b), a@b, np.multiply(a, b).sum())

[5, 7, 9]
[1 4 9]
32 32 32


In [26]:
x = np.array([[1, 2], [3, 4]])
print(x.reshape(4, 1))
y = np.array([[5, 6]])
print(np.concatenate((x, y.T), axis=1))
print(np.concatenate((x, y), axis=0))

[[1]
 [2]
 [3]
 [4]]
[[1 2 5]
 [3 4 6]]
[[1 2]
 [3 4]
 [5 6]]


In [33]:
arr = np.random.randint(-5, 11, (5, 7))
# print(arr)
print(arr.sum())
print(arr.min(axis=0), arr.max(axis=0))
print(arr.std(axis=1))
print(arr.var(axis=0))
print(arr.max(axis=0) - arr.min(axis=0))

96
[-5 -2 -4  0 -5 -1 -2] [ 7  7  3 10  7 10 10]
[4.71212071 4.76380914 5.6170295  3.54562104 3.05727637]
[25.44 10.16  5.6  12.96 25.6  17.84 25.84]
[12  9  7 10 12 11 12]


In [37]:
x = np.array([1, 2, 3])
print(x+5)
Y = np.random.rand(3, 3) * 2
print(y@np.random.randint((3, 5)))

[6 7 8]
[11]


In [40]:
arr = np.arange(1, 101)
mean = arr.mean()
print(arr[arr > mean])
q1 = np.percentile(arr, 25)
print(arr[arr < q1])
q3 = np.percentile(arr, 75)
print(arr[arr > q3])
print(arr[(arr % 2 == 0) & (arr % 3 != 0)])
print(arr[(arr % 5 == 0) & (arr % 2 != 0)])
print(arr[(arr % 2 != 0) & (arr % 3 == 0)])
print(arr[(arr % 2 == 0) & (arr % 5 != 0)])

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100]
[  2   4   8  10  14  16  20  22  26  28  32  34  38  40  44  46  50  52
  56  58  62  64  68  70  74  76  80  82  86  88  92  94  98 100]
[ 5 15 25 35 45 55 65 75 85 95]
[ 3  9 15 21 27 33 39 45 51 57 63 69 75 81 87 93 99]
[ 2  4  6  8 12 14 16 18 22 24 26 28 32 34 36 38 42 44 46 48 52 54 56 58
 62 64 66 68 72 74 76 78 82 84 86 88 92 94 96 98]


In [95]:
# 7) Sử dụng np.unique() để lọc ra các giá trị duy nhất từ một mảng đã cho. Đưa ra ví dụ minh họa. Đếm số lần xuất hiện các giá trị duy nhất đó.

arr = np.linspace(0, 10, 11)
condition = arr < 5
print(np.where(condition, 0, 1))
print(np.random.choice([1, 2, 3, 4, 5], 1))
arr.shape
A = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, 3)
print(np.linalg.solve(A, b))

# np.concatenate(): Chi hoat dong voi mang 2 chieu 
# np.vstack() và np.hstack() co  the hoat dong voi mang 1 chieu

heights = np.array([[160, 170, 155]])
weights = np.array([[60, 75, 52]])   # Shape: (1, 3)
print(heights.shape, weights.shape)
print(np.concatenate((heights, weights), axis=1))
print(np.vstack((heights, weights)))
print(np.concatenate((heights, weights), axis=0))
print(np.hstack((heights, weights)))

heights = np.array([160, 170, 155])
weights = np.array([60, 75, 52])   # Shape: (3,)
print(heights.shape, weights.shape)
try:
    print(np.concatenate((heights, weights), axis=1))
except Exception as e:
    print(e)

arr = np.random.randint(1, 10, (3, 3))
print(arr)
keys = np.unique(arr)
print(keys)
freq = {i: (arr == i).sum() for i in keys}
print(freq)

[0 0 0 0 0 1 1 1 1 1 1]
[2]
[ 2.5  0.  -1.5]
(1, 3) (1, 3)
[[160 170 155  60  75  52]]
[[160 170 155]
 [ 60  75  52]]
[[160 170 155]
 [ 60  75  52]]
[[160 170 155  60  75  52]]
(3,) (3,)
axis 1 is out of bounds for array of dimension 1
[[3 7 4]
 [3 4 6]
 [2 4 8]]
[2 3 4 6 7 8]
{2: 1, 3: 2, 4: 3, 6: 1, 7: 1, 8: 1}


In [106]:
A = np.array([[10,1,2],
              [9,7,4],
              [0,2,1]])

B = np.array([[2,3,4],
              [0,4,2],
              [3,2,1]])

print(A@B)
print(B@A.T@A@B.T)
print(A@B.T@B@A.T)

print(np.linalg.matrix_rank(A))
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(np.trace(A))

print(np.concatenate((A, B), axis=1))
print(np.concatenate((A, B), axis=0))
print(A.flatten())

softmax = lambda x: np.exp(x) / np.sum(np.exp(x), axis=0)
softmaxed = softmax(A)
print(softmax(A))
print(softmaxed.sum(axis = 1))
print(softmaxed.sum(axis = 1)/A.shape[1])
print(softmaxed.min(axis = 1))
print(softmaxed.max(axis = 1))


[[26 38 44]
 [30 63 54]
 [ 3 10  5]]
[[4086 2328 3579]
 [2328 1460 1942]
 [3579 1942 3206]]
[[2181 3523  560]
 [3523 6346 1135]
 [ 560 1135  225]]
3
16.999999999999993
[[-0.05882353  0.17647059 -0.58823529]
 [-0.52941176  0.58823529 -1.29411765]
 [ 1.05882353 -1.17647059  3.58823529]]
18
[[10  1  2  2  3  4]
 [ 9  7  4  0  4  2]
 [ 0  2  1  3  2  1]]
[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]
 [ 2  3  4]
 [ 0  4  2]
 [ 3  2  1]]
[10  1  2  9  7  4  0  2  1]
[[7.31034316e-01 2.45611490e-03 1.14195199e-01]
 [2.68932495e-01 9.90867473e-01 8.43794734e-01]
 [3.31889066e-05 6.67641251e-03 4.20100661e-02]]
[0.84768563 2.1035947  0.04871967]
[0.28256188 0.70119823 0.01623989]
[2.45611490e-03 2.68932495e-01 3.31889066e-05]
[0.73103432 0.99086747 0.04201007]
